 stages:
    - build
    - deploy

build:
  stage: build
  image: node:latest
  scripts:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - ssh -i $SSH_ID_RSA_PUB $SSH_USER@$SSH_SERVER 
  script:
    - scp dist $SSH_USER@$SSH_SERVER:$PROJECT_PATH
  only:
    - main